/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dao.TransacaoDAO;
import dao.UsuarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import mapper.Transacao;
import mapper.Usuario;

/**
 *
 * @author fabio
 */
public class Transacao_form extends javax.swing.JFrame {

    /**
     * Creates new form Transacao_form
     */
    Usuario usuario = new Usuario();
    Menu_form mf;
    Transacao transacao = new Transacao();

    public Transacao_form(Usuario u, Menu_form m) {
        initComponents();
        preencherTabela();
        jB_salvar.setVisible(true);
        jB_atualizar.setVisible(false);
        usuario = u;
        mf = m;
        preencherSaldo(usuario);
    }

    private Transacao_form() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Menu_form getMf() {
        return mf;
    }

    public void setMf(Menu_form mf) {
        this.mf = mf;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jT_id = new javax.swing.JTextField();
        jT_descricao = new javax.swing.JTextField();
        jT_quantia = new javax.swing.JTextField();
        jF_data = new javax.swing.JFormattedTextField();
        jC_categoria = new javax.swing.JComboBox<>();
        jB_salvar = new javax.swing.JButton();
        jB_atualizar = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jT_idtransacao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela_transacao = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jL_saldo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jF_datap = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jC_categoriap = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cadastro de Transações");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID Usuário:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Quantia:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Data:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Categoria:");

        jT_id.setEditable(false);
        jT_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_idActionPerformed(evt);
            }
        });

        jT_descricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jT_quantia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_quantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_quantiaActionPerformed(evt);
            }
        });

        try {
            jF_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_data.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jC_categoria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jC_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRADA", "SAIDA" }));

        jB_salvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });

        jB_atualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_atualizar.setText("Atualizar");
        jB_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_atualizarActionPerformed(evt);
            }
        });

        jB_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_cancelar.setText("Cancelar");
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("ID Transação:");

        jT_idtransacao.setEditable(false);
        jT_idtransacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jT_idtransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_idtransacaoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Voltar ao Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jT_descricao)
                            .addComponent(jT_quantia)
                            .addComponent(jF_data)
                            .addComponent(jC_categoria, 0, 200, Short.MAX_VALUE)
                            .addComponent(jT_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT_idtransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_salvar)
                        .addGap(18, 18, 18)
                        .addComponent(jB_atualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jB_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jT_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jT_idtransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_quantia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jF_data, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jC_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_salvar)
                    .addComponent(jB_atualizar)
                    .addComponent(jB_cancelar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(76, 76, 76))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Pesquisar por data");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesquisar_1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTabela_transacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTabela_transacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_TRANSACAO", "DESCRIÇÃO", "QUANTIA", "DATA", "CATEGORIA", "ID_USUARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabela_transacao);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Novo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Excluir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jL_saldo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jL_saldo.setText("dfrwer");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Voltar ao Menu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        try {
            jF_datap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jF_datap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Pesquisar por categoria");

        jC_categoriap.setEditable(true);
        jC_categoriap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jC_categoriap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENTRADA", "SAIDA", " " }));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesquisar_1.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setText("Mostrar todas as transações");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jL_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7)
                                .addGap(424, 424, 424))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jF_datap, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC_categoriap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jF_datap)
                            .addComponent(jC_categoriap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Lista de Transações", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jT_quantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_quantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_quantiaActionPerformed

    //BOTAO SALVAR
    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        Transacao t = new Transacao();
        t.setDescricao(jT_descricao.getText());
        t.setQuantia(Double.parseDouble(jT_quantia.getText()));
        t.setData_transacao(jF_data.getText());
        t.setCategoria(jC_categoria.getSelectedItem().toString());
        t.setFK_id_usuario(usuario.getId_usuario());
        if (t.getCategoria().equals("ENTRADA")) {
            usuario.setSaldoTotal(usuario.getSaldoTotal() + t.getQuantia());
        } else if (t.getCategoria().equals("SAIDA")) {
            usuario.setSaldoTotal(usuario.getSaldoTotal() - t.getQuantia());
        }

        TransacaoDAO tdao = new TransacaoDAO();
        tdao.cadastrar(t, usuario);
        UsuarioDAO udao = new UsuarioDAO();
        udao.atualizar(usuario);
        preencherTabela();
        jL_saldo.setText("Saldo total: R$" + usuario.getSaldoTotal());

        this.getMf().dispose();

        Menu_form mfn = new Menu_form(usuario);
        mfn.setVisible(true);
        this.setVisible(true);

        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_jB_salvarActionPerformed

    //BOTAO CANCELAR
    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        jT_id.setText("");
        jT_descricao.setText("");
        jT_quantia.setText("");
        jF_data.setText("");
        jC_categoria.setSelectedItem(-1);
        jT_idtransacao.setText("");
        jB_atualizar.setVisible(false);
        jB_salvar.setVisible(true);


    }//GEN-LAST:event_jB_cancelarActionPerformed

    //BOTAO NOVO
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jT_id.setText("");
        jT_descricao.setText("");
        jT_quantia.setText("");
        jF_data.setText("");
        jC_categoria.setSelectedItem(-1);
        jT_idtransacao.setText("");
        jTabbedPane1.setSelectedIndex(0);
        jB_atualizar.setVisible(false);
        jB_salvar.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    //BOTAO EXCLUIR
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int opcao = jTabela_transacao.getSelectedRow();
        if (opcao >= 0) {
            Transacao t = new Transacao();
            t.setId_transacao(Integer.parseInt(jTabela_transacao.getValueAt(opcao, 0).toString()));
            t.setDescricao(jTabela_transacao.getValueAt(opcao, 1).toString());
            t.setQuantia(Double.parseDouble(jTabela_transacao.getValueAt(opcao, 2).toString()));
            t.setData_transacao(jTabela_transacao.getValueAt(opcao, 3).toString());
            t.setCategoria(jTabela_transacao.getValueAt(opcao, 4).toString());
            t.setFK_id_usuario(Integer.parseInt(jTabela_transacao.getValueAt(opcao, 5).toString()));

            TransacaoDAO tdao = new TransacaoDAO();
            tdao.excluir(t, usuario);
            preencherTabela();

            if (t.getCategoria().equals("ENTRADA")) {
                usuario.setSaldoTotal(usuario.getSaldoTotal() - t.getQuantia());
            } else if (t.getCategoria().equals("SAIDA")) {
                usuario.setSaldoTotal(usuario.getSaldoTotal() + t.getQuantia());
            }
            UsuarioDAO udao = new UsuarioDAO();
            udao.atualizar(usuario);

            jL_saldo.setText("Saldo total: R$" + usuario.getSaldoTotal());

            this.getMf().dispose();

            Menu_form mfn = new Menu_form(usuario);
            mfn.setVisible(true);
            this.setVisible(true);

            jTabbedPane1.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    //BOTAO EDITAR
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int opcao = jTabela_transacao.getSelectedRow();
        if (opcao >= 0) {

            jT_id.setText((jTabela_transacao.getValueAt(opcao, 5).toString()));
            jT_descricao.setText(jTabela_transacao.getValueAt(opcao, 1).toString());
            jT_quantia.setText((jTabela_transacao.getValueAt(opcao, 2).toString()));
            jF_data.setText(jTabela_transacao.getValueAt(opcao, 3).toString());
            jC_categoria.setSelectedItem(jTabela_transacao.getValueAt(opcao, 4).toString());
            jT_idtransacao.setText(jTabela_transacao.getValueAt(opcao, 0).toString());

            jTabbedPane1.setSelectedIndex(0);
            jB_atualizar.setVisible(true);
            jB_salvar.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    //BOTAO ATUALIZAR
    private void jB_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_atualizarActionPerformed
        Transacao t = new Transacao();
        t.setId_transacao(Integer.parseInt(jT_idtransacao.getText()));
        t.setDescricao(jT_descricao.getText());
        t.setQuantia(Double.parseDouble(jT_quantia.getText()));
        t.setData_transacao(jF_data.getText());
        t.setCategoria(jC_categoria.getSelectedItem().toString());
        t.setFK_id_usuario(Integer.parseInt(jT_id.getText()));

        TransacaoDAO tdao = new TransacaoDAO();
        tdao.atualizar(t, usuario);
        preencherTabela();
        jL_saldo.setText("Saldo total: R$" + usuario.getSaldoTotal());
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_jB_atualizarActionPerformed

    private void jT_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_idActionPerformed

    }//GEN-LAST:event_jT_idActionPerformed

    //BOTAO VOLTAR AO MENU TRANSACAO
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //BOTAO SAIR TRANSACAO
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jT_idtransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_idtransacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_idtransacaoActionPerformed

    //BOTAO VOLTAR AO MENU LISTA TRANSACAO
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    //BOTAI SAIR LISTA TRANSACAO
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    //BOTAO DE PESQUISA POR DATA
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        preencherTabelaData(jF_datap.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    //botao pesquisar por categoria
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        preencherTabelaCategoria(jC_categoriap.getSelectedItem().toString());
    }//GEN-LAST:event_jButton9ActionPerformed

    //BOTAO PESQUISAR TODAS AS TRANSACOES
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        preencherTabela();
    }//GEN-LAST:event_jButton10ActionPerformed

    //PREENCHE TABELA COM TRANSACOES
    public void preencherTabela() {
        TransacaoDAO tdao = new TransacaoDAO();
        List<Transacao> listaTransacao = tdao.listarTodos();
        DefaultTableModel tabelaT = (DefaultTableModel) jTabela_transacao.getModel();
        tabelaT.setRowCount(0);
        for (Transacao t : listaTransacao) {
            tabelaT.addRow(new Object[]{t.getId_transacao(), t.getDescricao(), t.getQuantia(), t.getData_transacao(), t.getCategoria(), t.getFK_id_usuario()});
        }

    }

    //PREENCHE TABELA COM DATA PESQUISADA
    public void preencherTabelaData(String data) {
        TransacaoDAO tdao = new TransacaoDAO();
        List<Transacao> listaTransacao = tdao.buscarData(data);
        DefaultTableModel tabelaT = (DefaultTableModel) jTabela_transacao.getModel();
        tabelaT.setRowCount(0);
        listaTransacao.forEach(t -> {
            tabelaT.addRow(new Object[]{t.getId_transacao(), t.getDescricao(), t.getQuantia(), t.getData_transacao(), t.getCategoria(), t.getFK_id_usuario()});
        });

    }
    
    //PREENCHE TABELA COM CATEGORIA PESQUISADA
    public void preencherTabelaCategoria(String categoria) {
        TransacaoDAO tdao = new TransacaoDAO();
        List<Transacao> listaTransacao = tdao.buscarCategoria(categoria);
        DefaultTableModel tabelaT = (DefaultTableModel) jTabela_transacao.getModel();
        tabelaT.setRowCount(0);
        listaTransacao.forEach(t -> {
            tabelaT.addRow(new Object[]{t.getId_transacao(), t.getDescricao(), t.getQuantia(), t.getData_transacao(), t.getCategoria(), t.getFK_id_usuario()});
        });

    }

    public void preencherSaldo(Usuario usuario) {
        jL_saldo.setText("Saldo total: R$" + usuario.getSaldoTotal());
    }

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContasPagar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContasPagar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContasPagar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContasPagar_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transacao_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_atualizar;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jC_categoria;
    private javax.swing.JComboBox<String> jC_categoriap;
    private javax.swing.JFormattedTextField jF_data;
    private javax.swing.JFormattedTextField jF_datap;
    private javax.swing.JLabel jL_saldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_descricao;
    private javax.swing.JTextField jT_id;
    private javax.swing.JTextField jT_idtransacao;
    private javax.swing.JTextField jT_quantia;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTabela_transacao;
    // End of variables declaration//GEN-END:variables
}
